* Use native http_build_query() to build query string (PHP 5, PHP 7, PHP 8)
sveawebpay/php-integration pull request #96
Opened 2021-07-28 21:07 UTC by timint

No need to invent the wheel 😁

2021-09-06 12:16 UTC, alexanderwiden95 requested changes

2021-09-06 12:16 UTC, alexanderwiden95 commented on src/HostedService/HostedRequest.php
> +        $fieldsString = http_build_query($fields, '', '&');
```suggestion
        $fieldsString = urldecode(http_build_query($fields));
```

2021-09-06 15:19 UTC, timint commented
You can't urldecode a complete url. urldecode is for parameter values. Why would you need decode?

2021-09-06 15:33 UTC, alexanderwiden95 commented
`$fieldsString` is the arguments passed in `CURLOPT_POSTFIELDS`, not the complete URL

2021-09-06 15:37 UTC, timint commented
My misstake, yes it's the post params only.
I mean why would you urldecode them? This is a serialized string.
What would you do if any of the values holds the characters [ ] = ?

Invalid: foo=abc&123
Valid: foo=abc%26123

2021-09-07 09:41 UTC, alexanderwiden95 commented
The problem is that "message" can contain signs such as "%2B" ("+"-sign) which will result in a incorrect formatted string if encoded.
In my testing the non-decoded `$fieldsString` results in a "311 (BAD_MAC)" since the "%2B" now isn't representing a plus sign.

You're correct in the fact that other characters such as []=?, and so on could make the call invalid.

2021-09-07 14:23 UTC, timint commented
That is alarming. The original code lines neither do urlencode. It seems like if Svea Ekonomi are not decoding the data on their end. Which requires the API user to send the query without encoding.

This should be escalated back to the API developers.  Will you do it?

2023-10-10 12:49 UTC, closed without merging